### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by GiacomoLaw** [chain-counter/chain-counter.github.io#1]

**Comment by GiacomoLaw** [comment]
I attempted to add them in [this](https://github.com/chain-counter/chain-counter.github.io/commit/fac649c7b43b5892e4b8a21fde5bbfefefeedc4d) commit, however it broke the standard buttons.

**Comment by Ralkage** [comment]
I'll give this a shot and QA it before submitting a PR.

My woman wishes for arrow up and down functionality and that is what she will get! (Also support for "W" and "S").

**Comment by GiacomoLaw** [comment]
Awesome, thank you!

**Comment by GiacomoLaw** [comment]
@Ralkage any update? Thanks!
